type FigmaVariablesExport = {
  collections: Array<{
    name: string;
    modes: string[];
    variables: Record<string, unknown>;
  }>;
};

type LocaleMap = Record<string, { code: string; filename: string }>;

const DEFAULT_LOCALE_MAP: LocaleMap = {
  "🇺🇸 English": { code: "en", filename: "English" },
  "🇮🇩 Indonesian": { code: "id", filename: "Indonesian" },
  "🇯🇵 Japanese": { code: "ja", filename: "Japanese" },
  "🇰🇷 Korean": { code: "ko", filename: "Korean" },
  "🇨🇳 Chinese": { code: "zh", filename: "Chinese" },
  "🇪🇸 Spanish": { code: "es", filename: "Spanish" },
  "🇫🇷 French": { code: "fr", filename: "French" },
  "🇩🇪 German": { code: "de", filename: "German" },
  "🇵🇹 Portuguese": { code: "pt", filename: "Portuguese" },
  "🇷🇺 Russian": { code: "ru", filename: "Russian" },
  "🇹🇷 Turkish": { code: "tr", filename: "Turkish" },
  "🇻🇳 Vietnamese": { code: "vi", filename: "Vietnamese" },
  "🇹🇭 Thai": { code: "th", filename: "Thai" },
  "🇲🇾 Malay": { code: "ms", filename: "Malay" },
  "🇮🇳 Hindi": { code: "hi", filename: "Hindi" },
};

function toCamelCase(key: string): string {
  return key
    .replace(/[-_\s]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ""))
    .replace(/^(.)/, (char) => char.toLowerCase())
    .replace(/[^\w]/g, "")
    .replace(/([a-z])([A-Z])/g, "$1$2")
    .split(/(?=[A-Z])/)
    .join("")
    .replace(/([a-z])([A-Z])/g, "$1$2")
    .replace(/^([A-Z])/, (char) => char.toLowerCase());
}

interface ParsedVariable {
  key: string;
  value: string;
}

function traverseVariables(
  obj: Record<string, unknown>,
  prefix: string[] = []
): ParsedVariable[] {
  const result: ParsedVariable[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const currentPath = [...prefix, key];

    if (
      value &&
      typeof value === "object" &&
      "type" in (value as Record<string, unknown>) &&
      "values" in (value as Record<string, unknown>)
    ) {
      const node = value as Record<string, unknown>;
      if (node.type === "string" && node.values && typeof node.values === "object") {
        const values = node.values as Record<string, unknown>;
        const combinedKey = toCamelCase(currentPath.join(""));
        result.push({ key: combinedKey, value: "" });
        continue;
      }
    }

    if (value && typeof value === "object" && !Array.isArray(value)) {
      result.push(...traverseVariables(value as Record<string, unknown>, currentPath));
    }
  }

  return result;
}

function flattenVariables(
  variables: Record<string, unknown>,
  modes: string[]
): Record<string, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};

  for (const mode of modes) {
    result[mode] = {};
  }

  function traverse(
    obj: Record<string, unknown>,
    path: string[] = []
  ): void {
    for (const [key, value] of Object.entries(obj)) {
      const currentPath = [...path, key];

      if (
        value &&
        typeof value === "object" &&
        "type" in (value as Record<string, unknown>) &&
        (value as Record<string, unknown>).type === "string" &&
        "values" in (value as Record<string, unknown>)
      ) {
        const node = value as Record<string, unknown>;
        const values = node.values as Record<string, unknown>;
        const flattenedKey = toCamelCase(currentPath.join(""));

        for (const mode of modes) {
          if (mode in values && typeof values[mode] === "string") {
            result[mode][flattenedKey] = values[mode] as string;
          }
        }
      } else if (value && typeof value === "object" && !Array.isArray(value)) {
        traverse(value as Record<string, unknown>, currentPath);
      }
    }
  }

  traverse(variables);
  return result;
}

export interface SyncStringsOutput {
  webJson: Record<string, Record<string, string>>;
  flutterArb: Record<string, Record<string, string>>;
  localeMap: LocaleMap;
}

export function parseFigmaVariables(
  input: FigmaVariablesExport,
  customLocaleMap?: LocaleMap
): SyncStringsOutput {
  const localeMap = { ...DEFAULT_LOCALE_MAP, ...customLocaleMap };
  const webJson: Record<string, Record<string, string>> = {};
  const flutterArb: Record<string, Record<string, string>> = {};

  for (const collection of input.collections) {
    const { modes, variables } = collection;

    const flattenedByMode = flattenVariables(variables, modes);

    for (const [mode, strings] of Object.entries(flattenedByMode)) {
      if (!webJson[mode]) {
        webJson[mode] = {};
        flutterArb[mode] = {};
      }

      Object.assign(webJson[mode], strings);

      const localeInfo = localeMap[mode];
      if (localeInfo) {
        flutterArb[mode] = {
          [`@@locale`]: localeInfo.code,
          [`@@context`]: "Generated by SyncStrings",
          ...strings,
        };
      }
    }
  }

  return { webJson, flutterArb, localeMap };
}

export function buildOutputFiles(
  input: FigmaVariablesExport,
  customLocaleMap?: LocaleMap
): {
  files: Array<{ name: string; content: string; locale: string }>;
} {
  const { webJson, flutterArb, localeMap } = parseFigmaVariables(input, customLocaleMap);
  const files: Array<{ name: string; content: string; locale: string }> = [];

  for (const [mode, strings] of Object.entries(webJson)) {
    const localeInfo = localeMap[mode];
    if (!localeInfo) continue;

    files.push({
      name: `${localeInfo.filename}.json`,
      content: JSON.stringify(strings, null, 2),
      locale: localeInfo.code,
    });

    files.push({
      name: `app_${localeInfo.code}.arb`,
      content: JSON.stringify(flutterArb[mode], null, 2),
      locale: localeInfo.code,
    });
  }

  return { files };
}