import { useState, useEffect } from "react";
import { useFetcher } from "react-router";
import type { Route } from "./+types/home";
import { parseFigmaVariables } from "../lib/figma-variables-parser";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "SyncStrings" },
    { name: "description", content: "Generate ARB and JSON localization files from Figma" },
  ];
}

type ActionResult =
  | { success: true; files: Array<{ name: string; content: string }> }
  | { success?: never; error: string };

export async function action({ request }: Route.ActionArgs) {
  const formData = await request.formData();
  const mode = formData.get("mode") as string;

  if (mode === "upload") {
    const file = formData.get("jsonFile") as File | null;

    if (!file || file.size === 0) {
      return { error: "Error: Please upload a valid JSON file." };
    }

    try {
      const text = await file.text();
      const json = JSON.parse(text);

      // Check if it's a Figma Variables export (has collections)
      if (json.collections && Array.isArray(json.collections)) {
        const result = parseFigmaVariables(json);

        const files: Array<{ name: string; content: string }> = [];
        for (const [mode, strings] of Object.entries(result.webJson)) {
          const localeInfo = result.localeMap[mode];
          if (!localeInfo) continue;

          files.push({
            name: `${localeInfo.filename}.json`,
            content: JSON.stringify(strings, null, 2),
          });
          files.push({
            name: `app_${localeInfo.code}.arb`,
            content: JSON.stringify(result.flutterArb[mode], null, 2),
          });
        }

        if (files.length === 0) {
          return { error: "Error: No valid string values found in JSON." };
        }

        return { success: true, files };
      }

      // Legacy simple JSON format (flat key-value)
      const webJson: Record<string, string> = {};
      const mobileArb: Record<string, string> = {
        "@@locale": "en",
        "@@context": "Generated by SyncStrings",
      };

      function extractKeys(obj: Record<string, unknown>, prefix = "") {
        for (const [key, value] of Object.entries(obj)) {
          const newKey = prefix ? `${prefix}_${key}` : key;
          if (typeof value === "string") {
            webJson[newKey] = value;
            mobileArb[newKey] = value;
          } else if (typeof value === "object" && value !== null) {
            extractKeys(value as Record<string, unknown>, newKey);
          }
        }
      }

      extractKeys(json);

      if (Object.keys(webJson).length === 0) {
        return { error: "Error: No valid string values found in JSON." };
      }

      return {
        success: true,
        files: [
          { name: "en.json", content: JSON.stringify(webJson, null, 2) },
          { name: "app_en.arb", content: JSON.stringify(mobileArb, null, 2) },
        ],
      };
    } catch {
      return { error: "Error: The uploaded file is not valid JSON." };
    }
  }

  if (mode === "api") {
    const pat = formData.get("pat") as string;
    const nodeLink = formData.get("nodeLink") as string;

    const urlMatch = nodeLink.match(/figma\.com\/design\/([a-zA-Z0-9]+)/);
    const nodeIdMatch = nodeLink.match(/node-id=([^&]+)/);

    if (!urlMatch || !nodeIdMatch) {
      return { error: "Error: Invalid Figma link. Please ensure it contains a node-id." };
    }

    const fileKey = urlMatch[1];
    const nodeId = nodeIdMatch[1].replace("-", ":");

    try {
      const figmaResponse = await fetch(
        `https://api.figma.com/v1/files/${fileKey}/nodes?ids=${nodeId}`,
        {
          headers: {
            "X-Figma-Token": pat,
          },
        }
      );

      if (figmaResponse.status === 403) {
        return { error: "Error: Invalid Personal Access Token or insufficient permissions." };
      }

      if (!figmaResponse.ok) {
        return { error: `Error: Figma API returned ${figmaResponse.status}.` };
      }

      const figmaData: {
        nodes?: Record<string, { document: Record<string, unknown> }>;
      } = await figmaResponse.json();

      const webJson: Record<string, string> = {};
      const mobileArb: Record<string, string> = {
        "@@locale": "en",
        "@@context": "Generated by SyncStrings",
      };

      function findTextNodes(node: Record<string, unknown>) {
        if (node.type === "TEXT") {
          const name = node.name as string;
          const characters = node.characters as string;
          if (name && characters) {
            const key = name.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
            webJson[key] = characters;
            mobileArb[key] = characters;
          }
        }

        const children = node.children as Array<Record<string, unknown>> | undefined;
        if (children && Array.isArray(children)) {
          for (const child of children) {
            findTextNodes(child);
          }
        }
      }

      const nodes = figmaData.nodes?.[nodeId]?.document;
      if (nodes) {
        findTextNodes(nodes);
      }

      if (Object.keys(webJson).length === 0) {
        return { error: "Error: No TEXT nodes found in the specified Figma frame." };
      }

      return {
        success: true,
        files: [
          { name: "en.json", content: JSON.stringify(webJson, null, 2) },
          { name: "app_en.arb", content: JSON.stringify(mobileArb, null, 2) },
        ],
      };
    } catch (err) {
      return { error: `Error: Failed to fetch from Figma. ${err instanceof Error ? err.message : "Unknown error"}` };
    }
  }

  return { error: "Error: Invalid mode." };
}

function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function Home() {
  const [mode, setMode] = useState<"api" | "upload">("upload");
  const fetcher = useFetcher<ActionResult>();

  const isProcessing = fetcher.state !== "idle";

  // Handle successful download
  useEffect(() => {
    if (fetcher.data && "files" in fetcher.data) {
      for (const file of fetcher.data.files) {
        downloadFile(file.content, file.name);
      }
    }
  }, [fetcher.data]);

  return (
    <div className="min-h-screen bg-[#F8FAFC] flex items-center justify-center p-6">
      <div className="w-full max-w-lg">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-semibold text-[#191c1e] tracking-tight">
            SyncStrings
          </h1>
          <p className="mt-2 text-sm text-[#64748b]">
            Generate localization files from Figma
          </p>
        </div>

        {/* Main Card */}
        <div className="bg-white rounded-lg border border-[#E2E8F0] shadow-sm">
          {/* Mode Toggle */}
          <div className="flex border-b border-[#E2E8F0]">
            <button
              type="button"
              onClick={() => setMode("upload")}
              className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                mode === "upload"
                  ? "text-[#2563EB] border-b-2 border-[#2563EB] bg-[#F8FAFC]"
                  : "text-[#64748b] hover:text-[#191c1e] hover:bg-[#F8FAFC]"
              }`}
            >
              Upload JSON
            </button>
            <button
              type="button"
              onClick={() => setMode("api")}
              className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                mode === "api"
                  ? "text-[#2563EB] border-b-2 border-[#2563EB] bg-[#F8FAFC]"
                  : "text-[#64748b] hover:text-[#191c1e] hover:bg-[#F8FAFC]"
              }`}
            >
              Fetch via API
            </button>
          </div>

          {/* Form */}
          <div className="p-6">
            {mode === "upload" && (
              <fetcher.Form
                method="post"
                encType="multipart/form-data"
                className="space-y-4"
              >
                <input type="hidden" name="mode" value={mode} />

                <div>
                  <label
                    htmlFor="jsonFile"
                    className="block text-sm font-medium text-[#191c1e] mb-2"
                  >
                    Figma Variables JSON
                  </label>
                  <input
                    type="file"
                    id="jsonFile"
                    name="jsonFile"
                    accept=".json"
                    className="w-full px-3 py-2 border border-[#E2E8F0] rounded-lg text-sm text-[#191c1e]
                               file:mr-4 file:py-1 file:px-3 file:rounded file:border-0
                               file:text-sm file:font-medium file:bg-[#F8FAFC] file:text-[#191c1e]
                               hover:file:bg-[#E2E8F0] cursor-pointer
                               focus:outline-none focus:ring-2 focus:ring-[#2563EB]/40 focus:border-[#2563EB]"
                  />
                  <p className="mt-1 text-xs text-[#64748b]">
                    Upload exported Figma Variables JSON
                  </p>
                </div>

                <button
                  type="submit"
                  disabled={isProcessing}
                  className="w-full py-2.5 px-4 bg-[#2563EB] text-white text-sm font-medium rounded-lg
                             hover:bg-[#1D4ED8] transition-colors
                             disabled:opacity-50 disabled:cursor-not-allowed
                             focus:outline-none focus:ring-2 focus:ring-[#2563EB]/40 focus:ring-offset-2"
                >
                  {isProcessing ? "Processing..." : "Generate Files"}
                </button>
              </fetcher.Form>
            )}

            {mode === "api" && (
              <fetcher.Form
                method="post"
                encType="multipart/form-data"
                className="space-y-4"
              >
                <input type="hidden" name="mode" value={mode} />

                <div>
                  <label
                    htmlFor="pat"
                    className="block text-sm font-medium text-[#191c1e] mb-2"
                  >
                    Figma Personal Access Token
                  </label>
                  <input
                    type="password"
                    id="pat"
                    name="pat"
                    placeholder="figd_xxxxxxxxxxxxxx"
                    className="w-full px-3 py-2 border border-[#E2E8F0] rounded-lg text-sm text-[#191c1e]
                               placeholder:text-[#94A3B8]
                               focus:outline-none focus:ring-2 focus:ring-[#2563EB]/40 focus:border-[#2563EB]"
                  />
                </div>

                <div>
                  <label
                    htmlFor="nodeLink"
                    className="block text-sm font-medium text-[#191c1e] mb-2"
                  >
                    Figma Node Link
                  </label>
                  <input
                    type="text"
                    id="nodeLink"
                    name="nodeLink"
                    placeholder="https://www.figma.com/design/..."
                    className="w-full px-3 py-2 border border-[#E2E8F0] rounded-lg text-sm text-[#191c1e]
                               placeholder:text-[#94A3B8]
                               focus:outline-none focus:ring-2 focus:ring-[#2563EB]/40 focus:border-[#2563EB]"
                  />
                  <p className="mt-1 text-xs text-[#64748b]">
                    Link to Figma frame containing text layers
                  </p>
                </div>

                <button
                  type="submit"
                  disabled={isProcessing}
                  className="w-full py-2.5 px-4 bg-[#2563EB] text-white text-sm font-medium rounded-lg
                             hover:bg-[#1D4ED8] transition-colors
                             disabled:opacity-50 disabled:cursor-not-allowed
                             focus:outline-none focus:ring-2 focus:ring-[#2563EB]/40 focus:ring-offset-2"
                >
                  {isProcessing ? "Processing..." : "Generate Files"}
                </button>
              </fetcher.Form>
            )}

            {/* Feedback Area */}
            {fetcher.data && "error" in fetcher.data && (
              <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-sm text-red-700">{fetcher.data.error}</p>
              </div>
            )}

            {fetcher.data && "files" in fetcher.data && (
              <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded-lg">
                <p className="text-sm text-green-700">
                  Files generated successfully! Downloading...
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <p className="text-center text-xs text-[#94A3B8] mt-6">
          Outputs: en.json (Web) and app_en.arb (Flutter)
        </p>
      </div>
    </div>
  );
}